Algoritmo "Contador_Simples"
// 
//  
// Descrição   : CONTADOR
// Autor(a)    : HERCULES R SANTOS
// Data atual  : 28/12/2021
Var
// Seção de Declarações das variáveis 

        contador, limite : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 



       contador <- 0
       limite <- 10
       enquanto (contador <= 10) faca
       
       
       escreval("...", contador)
       contador <- contador +1
       
       fimenquanto

Fimalgoritmo