Algoritmo "Estrutura_Para_Resolvido_Exercicio"
// 
//  
// Descrição   : Estrutura Para
// Autor(a)    : HERCULES R SANTOS
// Data atual  : 28/12/2021
Var
// Seção de Declarações das variáveis 

        c,n,s : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

      c <- 1
      s <- 0

      para C<-1 ate 5 faca
      escreval("DIGITE O VALOR")
      leia(n)
      s <- s + n
      fimpara
      escreval("A SOMA TOTAL FOI :",s)
      
Fimalgoritmo