Algoritmo "Exercicio02_Procedimento"

// Autor(a)    : HERCULES R SANTOS
// Data atual  : 29/12/2021
Var

   x,y: inteiro

PROCEDIMENTO exercicio(a, b: INTEIRO)
Inicio
         escreval("ESSA VARIAVEL RECEBE DA VALOR 1 :", a)
         escreval("ESSA VARIAVEL RECEBE DO VALOR 2 :", b)
         escreval("O TOTAL DO PROCEDIMENTO DAS VARIAVEIS FOI :", a + b)
fimprocedimento
Inicio

      y <- 50
      x <- 40
      exercicio(x, y)

Fimalgoritmo