Algoritmo "Exercicio3_Estrutura_Procedimento"

Var

   x,z,entrada2,entrada : inteiro

procedimento rota( f, g : inteiro)
Inicio
   escreval("-------------------------")
   escreval("PRIMEIRO VALOR :",f)
   escreval("SEGUNDO VALOR :",g)
   escreval("A SOMA TOTAL FOI: ", f + g)
   escreval("-------------------------")



fimprocedimento


Inicio

    x <- 8
    z <- 2
    

   rota(x,z )

Fimalgoritmo