Algoritmo "Variavel mensagem "

Var
      a, b, c: inteiro


Inicio

       escreval(verdadeiro e verdadeiro)
       escreval(verdadeiro e falso)
       escreval(falso e verdadeiro)
       escreval(falso e falso)
       
       escreval(verdadeiro ou verdadeiro)
       escreval(verdadeiro ou falso)
       escreval(falso ou falso)
       escreval(falso ou verdadeiro)
       //OPERADORES LOGICOS E e OU



Fimalgoritmo