Algoritmo "semnome"
// *
// *
// Descrição   : PROCEDIMENTOS
// Autor(a)    : HERCULES R SANTOS
// Data atual  : 29/12/2021
Var

   g,h:inteiro

Procedimento Soma (x, y: Inteiro)
Inicio
   x <- x + 6
   y <- y + 8

   escreval("VALOR TOTAL =", x + y)
   escreval("O VALOR DE X = ", x)
   escreval("O VALOR DE Y = ", y)

fimprocedimento
inicio
   g <- 2
   h <- 4

   Soma (g, h)
   escreval("VALOR DE G =",g)
   escreval("VALOR DE H =",h)

Fimalgoritmo